### ISSUE TITLE
Installing “Sublime-Style-Column-Selection@1.7.4” failed

### ISSUE THREAD

**Issue by FrankSong28** [bigfive/atom-sublime-select#152]
Installing “Sublime-Style-Column-Selection@1.7.4” failed.Hide output…
(node:29981) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/frank/.atom/packages/Sublime-Style-Column-Selection/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at Proxy.fs.readFileSync (fs.js:568:33)
    at Proxy.fs.readFileSync (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:476:42
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)

**Comment by xyw19870905** [comment]
the same as me

**Comment by dougxn** [comment]
ditto: atom 1.23.1 x64

**Comment by garethallenstringer** [comment]
Similar to the issue I and others are experiencing at #151

**Comment by Vertigoooo** [comment]
Same

**Comment by Visero** [comment]
Use apm to install ''apm install sublime-style-column-selection'', can solve
