### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

### ISSUE THREAD

**Issue by MiquelAdell** [bigfive/atom-sublime-select#37]
[Enter steps to reproduce below:]
1. Column select using [ALT] + click

I can't see any more specifics to the situation.

The file where I'm selecting is 700 lines long.
I get the error from the moment I click I don't have to drag to get the error.

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.1
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.2.3
### Stack Trace

Uncaught TypeError: Cannot read property 'getDOMNode' of undefined

```
At /Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:984

TypeError: Cannot read property 'getDOMNode' of undefined
  at [object Object].module.exports.React.createClass.pixelPositionForMouseEvent (/Applications/Atom.app/Contents/Resources/app/src/text-editor-component.js:984:40)
  at [object Object].boundMethod [as pixelPositionForMouseEvent] (/Applications/Atom.app/Contents/Resources/app/node_modules/react-atom-fork/lib/ReactCompositeComponent.js:1295:21)
  at /Users/miquel/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:76:42
  at atom-text-editor.<anonymous> (/Users/miquel/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:49:23)

```
### Commands

```
  2x -0:26.7 editor:newline (atom-text-editor.editor.is-focused)
     -0:22.4 core:backspace (atom-text-editor.editor.is-focused)
     -0:17.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:15.8 core:move-up (atom-text-editor.editor.is-focused)
     -0:15.2 core:move-down (atom-text-editor.editor.is-focused)
     -0:15.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.8 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:14.3 core:copy (atom-text-editor.editor.is-focused)
     -0:14.2 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:13.6 core:paste (atom-text-editor.editor.is-focused)
     -0:13.4 core:move-down (atom-text-editor.editor.is-focused)
     -0:12.8 core:move-right (atom-text-editor.editor.is-focused)
     -0:04.9 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:04.5 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:04.0 core:move-up (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "wrap-guide",
      "whitespace",
      "preview-tabs",
      "term2",
      "atom-ctags"
    ],
    "projectHome": "/Users/miquel/code",
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
auto-detect-indentation, v0.3.0
autocomplete-plus, v2.2.0
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
compare-files, v0.4.1
git-tab-status, v1.5.3
highlight-selected, v0.9.0
linter, v0.11.1
minimap, v4.3.1
minimap-find-and-replace, v4.0.0
minimap-git-diff, v4.0.0
minimap-highlight-selected, v4.1.0
minimap-selection, v4.1.0
project-manager, v1.15.5
remember-session, v0.5.1
remote-sync, v2.4.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by bigfive** [comment]
Hmm, I cant seem to reproduce this. Are you still having the problem?

**Comment by MiquelAdell** [comment]
Nope, something fixed this but I can't know what or when because for a long time I stoped using [alt]+click+drag and used selection+[cmd]+[shift]+[L]

Thanks anyway!
