### ISSUE TITLE
Uncaught TypeError: Cannot read property 'matchesParams' of undefined

### ISSUE THREAD

**Issue by stevencombs** [bigfive/atom-sublime-select#58]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.3.0
### Stack Trace

Uncaught TypeError: Cannot read property 'matchesParams' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:134

TypeError: Cannot read property 'matchesParams' of undefined
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:134:21
  at Set.forEach (native)
  at MarkerStore.module.exports.MarkerStore.findMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:130:17)
  at TextBuffer.module.exports.TextBuffer.findMarkers (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:686:31)
  at DisplayBuffer.module.exports.DisplayBuffer.findFoldMarkers (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1416:26)
  at DisplayBuffer.module.exports.DisplayBuffer.foldsContainingBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:882:20)
  at DisplayBuffer.module.exports.DisplayBuffer.unfoldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:828:20)
  at TextEditor.module.exports.TextEditor.unfoldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2408:33)
  at TextEditor.module.exports.TextEditor.destroyFoldsContainingBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2484:12)
  at Selection.module.exports.Selection.setBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:108:21)
  at Selection.module.exports.Selection.setScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:92:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1697:29
  at TextEditor.module.exports.TextEditor.mergeSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1973:43)
  at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1947:35)
  at TextEditor.module.exports.TextEditor.setSelectedScreenRanges (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1690:19)
  at _selectBoxAroundCursors (/Users/stevencombs/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:127:18)
  at onRangeChange (/Users/stevencombs/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:80:9)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.selectionRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2065:27)
  at Selection.module.exports.Selection.screenRangeChanged (/Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:877:26)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/selection.js:43:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:270:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:65:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:390:20)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:339:12)
  at MarkerStore.module.exports.MarkerStore.restoreFromSnapshot (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker-store.js:204:20)
  at TextBuffer.module.exports.TextBuffer.revertToCheckpoint (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:775:26)
  at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:739:14)
  at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1147:26)
  at atom-text-editor.newCommandListeners.(anonymous function) (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:306:22)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:24.3.0 core:cut (atom-text-editor.editor.is-focused)
  2x -0:23.6.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -0:21.5.0 core:move-up (atom-text-editor.editor.is-focused)
  2x -0:19.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:19.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:18.3.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:copy (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "tidy-markdown"
    ],
    "themes": [
      "dark-flat-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.3.0
autoclose-html, v0.17.1
color-picker, v2.0.4
dark-flat-ui, v1.1.4
language-arduino, v0.2.1
linter, v0.12.6
markdown-scroll-sync, v0.4.0
markdown-table-formatter, v2.5.2
minimap, v4.9.4
sync-settings, v0.2.2
webbox-color, v0.5.7
wordcount, v2.2.2

# Dev
No dev packages
```

**Comment by bigfive** [comment]
I cant seem to reproduce this
