### ISSUE TITLE
Failed to activate the Sublime-Style-Column-Selection package

### ISSUE THREAD

**Issue by stephenpardy** [bigfive/atom-sublime-select#60]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [Sublime-Style-Column-Selection](https://github.com/bigfive/atom-sublime-select) package, v1.3.0

### Stack Trace

Failed to activate the Sublime-Style-Column-Selection package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Object.module.exports.activate (/Users/spardy/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:3:12)
  at Package.module.exports.Package.activateNow (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Users/spardy/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -3:39.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -3:05.9.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:13.5.0 application:open (ul.list-inline.tab-bar.inset-panel)
     -1:34.8.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:55.3.0 application:open (atom-text-editor.editor.is-focused)
     -0:24.2.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:20.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -0:18.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:16.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  2x -0:15.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:13.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:13.6.0 settings-view:view-installed-packages (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0

# Dev
No dev packages
```

**Comment by nemoDreamer** [comment]
:+1:

**Comment by bigfive** [comment]
I believe this is fixed in the new release
