### ISSUE TITLE
Failed to activate: Cannot read property 'eachEditorView' of undefined

### ISSUE THREAD

**Issue by PierreGUI** [bigfive/atom-sublime-select#61]
Steps to reproduce: open Atom editor 

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.4
**Thrown From**: [SublimeSelect](https://github.com/bigfive/atom-sublime-select) package, v0.4.2

### Stack Trace

Failed to activate the SublimeSelect package

```
At Cannot read property 'eachEditorView' of undefined

TypeError: Cannot read property 'eachEditorView' of undefined
  at Object.module.exports.activate (/Users/pierre/.atom/packages/SublimeSelect/lib/sublime-select.coffee:6:34)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
  at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
  at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:46)
  at Atom.module.exports.Atom.startEditorWindow (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:641:21)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:12:8)
  at Object.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:95:23)
  at window.onload (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ],
    "ignoredNames": [
      "build/",
      "build",
      "Resources/",
      "Resources"
    ],
    "disabledPackages": [
      "remember-session",
      "save-session"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
SublimeSelect, v0.4.2
coffee-compile, v0.16.1
docblockr, v0.7.2
highlight-selected, v0.10.1
pretty-json, v0.3.3
tabs-to-spaces, v0.11.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by bigfive** [comment]
I believe this is fixed in the new release
